apiVersion: v1 
kind: Pod
metadata: 
  name: redis-app-pod
  labels:
    name: redis-app-pod
    app: demo-voting

spec:
  containers:
  - name: redis
    image: redis
    ports: 
    - containerPort: 6379
